language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  email: false
  slack:
    secure: BRD/3z1LFp4Vh0HysGkSa54q+ED9TR2oISQ6HxY95lCZiLWGHDppSbJgHoy9FwE7l6RpNZmVOdYx32WLUG7Faoh3Qv8g4Ui2sn7X25BVSyl+7lvRygzpJT3Ipe/nJK291HiID/tLmb5/7j94BexZqexBWDkEMPeF+21N5xZRG8QpTOGCT5tA2+NCvaF7YFAbRX5w0PXfJxC3W4h7MhwQHVgnBRytzNp8P2l+lbezIfnkIS2F3rEYN5oT1S9mxrv9bSzFqtaCLkRWLqNGZ3rMn715qEeCrDjpdkkUiM8alWeHKkCcrhbhuNfvLNC1iiXUflyDq02liuA5eQ1r0e4TN0R33Z8FypUW3S62MLJD8pGRtd3Szr8Csy1ds/ALFLIXJiJDT7kt42OyyLossq0NRUANbFK9+mxc8Yxj3tEEnFw3hZXI63lEAskKuK9BT3X9/xCXrlu0k0FyK3EAXeu1n1mMlxBhtPKq9nJrivKaMOQww0CphM+N0KeqWqb4mtJ08fkBAaj+8CV15dEE+kVNR1d3yG6X4ub5vgWTYXgU6gwkPzLePHo9jrgPV3zTdaPx/ImNDWoZ2VTe/zUbu0w+GPI4RD4m/WGl3MvDASt+0AmGss+cybKAFxBO/nhmLvdSIQvWAc8qe5M87XaiF3cxLjmHt7XkmXZyBT3bplSm00E=
